### PR TITLE
Closes #224

### LINKED ISSUE #224: "property is less than" tests are failing for valid data
**Describe the bug**
property Is Less Than_match All and property Is Less Than_match Any tests are failing with reason of failure: "java.lang.AssertionError: XPath expression cannot be evaluated: xs:dateTime(ns1:beginLifespanVersion) lt xs:dateTime('2020-08-15T00:00:00Z')Invalid dateTime value "" (too short). "
The element beginLifespanVersion is indeed empty for some objects in the WFS but as the attribute is nillable and a nilReason value is provided, that should be valid IMHO.

**To Reproduce**
Validate [this WFS](https://haleconnect.com/ows/services/org.292.5c3d9005-8887-44d9-a72e-96cd0a7fffe4_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0) with the OGC Team Engine Validator.

**Expected behavior**
I would expect the handling of beginLifespanVersion to be valid.

**Screenshots**
grafik
grafik

### PR DESCRIPTION
**Pull request by bpross-52n**
Closes #224

### CODE REVIEW

**Review by dstenger — CHANGES_REQUESTED** [review]
When testing this branch with reference implementation https://cite.deegree.org/deegree-webservices-3.4.30/services/wfs200?service=WFS&request=GetCapabilities, one test is failing three times which was not failing before:
`property Is Less Than_match Any | No matching property value found for XPath: xs:dateTime(ns1:legalFoundationDate) lt xs:dateTime('2012-05-11T00:00:00Z').`

@bpross-52n Can you please check why this unexpected failure occurs?

**Comment by dstenger** [comment]
Meeting 2022-11-03:
One day is added to the filter to make sure that a feature is always returned.

**Comment by bpross-52n** [comment]
The following request to the reference implementation returns no features:

`
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="10" service="WFS"
                version="2.0.0">
   <wfs:Query xmlns:ns79="urn:x-inspire:specification:gmlas:ProtectedSites:3.0"
              typeNames="ns79:ProtectedSite">
      <Filter xmlns="http://www.opengis.net/fes/2.0">
         <PropertyIsLessThan matchAction="All" matchCase="true">
            <Literal>2012-05-13T00:00:00</Literal>
            <ValueReference xmlns:tns="urn:x-inspire:specification:gmlas:ProtectedSites:3.0">tns:legalFoundationDate</ValueReference>
         </PropertyIsLessThan>
      </Filter>
   </wfs:Query>
</wfs:GetFeature>
`
All the features have a legalFoundationDate of 2012-05-11T00:00:00, so that the features should IMHO be returned. You can check this using the following request:

`
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="20" service="WFS"
                version="2.0.0">
   <wfs:Query xmlns:ns79="urn:x-inspire:specification:gmlas:ProtectedSites:3.0"
              typeNames="ns79:ProtectedSite">
   </wfs:Query>
</wfs:GetFeature>
`

**Comment by dstenger** [comment]
Compared test with specs:

[Failing test](https://github.com/opengeospatial/ets-wfs20/blob/master/src/main/java/org/opengis/cite/iso19142/basic/filter/ComparisonOperatorTests.java#L89) references FilterEncoding spec: ISO 19143: 7.7

When checking the [ATS of the WFS 2.0 spec](http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#309), this test case should be part of test requirement `A.2.13 Predicate encoding` which is quite generic.

The FilterEncoding spec describes in chapter [7.7 Comparison operators](http://docs.opengeospatial.org/is/09-026r2/09-026r2.html#44) the different types of operators. PropertyIsLessThan is part of the [binary comparisons](http://docs.opengeospatial.org/is/09-026r2/09-026r2.html#48). On the other hand, temporal operators are defined in chapter [7.9 Temporal operators](http://docs.opengeospatial.org/is/09-026r2/09-026r2.html#64).
As chapter 7.7 just contains mathematical comparisons, temporal comparisons should, as far as I see, not be supported here.

Thus, my conclusion is that PropertyIsLessThan should not work for temporal values.

**Comment by dstenger** [comment]
@bpross-52n Can you please check if this PR can be closed as the corresponding issue is already closed?

**Comment by dstenger** [comment]
See https://github.com/opengeospatial/ets-wfs20/issues/224#issuecomment-1311672294 for reason.

**Pull request closed without merging**
