### PR TITLE
Closes #230

### LINKED ISSUE #230: NullPointerException when running v1.38 of the WFS compliance test
Hi, we have an automated test that runs the latest version of the WFS 2.0 compliance test against our WFS server implementation; this test started failing since v1.38, with the following exception:

CITE	>	[TestNG] Reporter com.occamlab.te.spi.executors.testng.EarlReporter@62fdb4a6 failed
CITE	>	java.lang.NullPointerException
CITE	>		at com.occamlab.te.spi.executors.testng.EarlReporter.isBasicConformanceClass(EarlReporter.java:451)
CITE	>		at com.occamlab.te.spi.executors.testng.EarlReporter.addTestRequirements(EarlReporter.java:240)
CITE	>		at com.occamlab.te.spi.executors.testng.EarlReporter.generateReport(EarlReporter.java:103)
CITE	>		at org.testng.TestNG.generateReports(TestNG.java:1135)
CITE	>		at org.testng.TestNG.run(TestNG.java:1081)
CITE	>		at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:137)
CITE	>		at org.opengis.cite.iso19142.TestNGController.doTestRun(TestNGController.java:142)
CITE	>		at org.opengis.cite.iso19142.TestNGController.main(TestNGController.java:82)

Could this be a regression?

### PR DESCRIPTION
**Pull request by bpross-52n**
Closes #230

### CODE REVIEW

**Review by dstenger — CHANGES_REQUESTED** [review]
Test of fix:
```
stenger@elsbeere:~/git/ets-wfs20/target$ export TE_BASE=""
stenger@elsbeere:~/git/ets-wfs20/target$ java -jar ets-wfs20-1.39-SNAPSHOT-aio.jar /home/stenger/test-run-props.xml
Nov 14, 2022 4:44:32 PM org.opengis.cite.iso19142.util.TestSuiteLogger log
INFORMATION: Using outputDirPath: /home/stenger
java.io.FileNotFoundException: /config.xml (Datei oder Verzeichnis nicht gefunden)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at com.occamlab.te.vocabulary.Config.<init>(Config.java:73)
	at com.occamlab.te.spi.executors.testng.EarlReporter.<init>(EarlReporter.java:95)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:965)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:914)
	at org.testng.TestNG.run(TestNG.java:1037)
	at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:137)
	at org.opengis.cite.iso19142.TestNGController.doTestRun(TestNGController.java:142)
	at org.opengis.cite.iso19142.TestNGController.main(TestNGController.java:82)
...
stenger@elsbeere:~/git/ets-wfs20/target$ export TE_BASE=/home/stenger/git/ets-wfs20/target/ets-wfs20-1.39-SNAPSHOT-ctl/wfs/2.0.0
stenger@elsbeere:~/git/ets-wfs20/target$ java -jar ets-wfs20-1.39-SNAPSHOT-aio.jar /home/stenger/test-run-props.xml
Nov 14, 2022 4:45:30 PM org.opengis.cite.iso19142.util.TestSuiteLogger log
INFORMATION: Using outputDirPath: /home/stenger
java.lang.NullPointerException
	at com.occamlab.te.vocabulary.Config.getElementsByTagName(Config.java:189)
	at com.occamlab.te.vocabulary.Config.<init>(Config.java:84)
	at com.occamlab.te.spi.executors.testng.EarlReporter.<init>(EarlReporter.java:95)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:965)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:914)
	at org.testng.TestNG.run(TestNG.java:1037)
	at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:137)
	at org.opengis.cite.iso19142.TestNGController.doTestRun(TestNGController.java:142)
	at org.opengis.cite.iso19142.TestNGController.main(TestNGController.java:82)
...
```

-> The problem regarding the config.xml is solved. However, there is a new StackTrace now (the one at the bottom).
@bpross-52n Can you please check why the new StackTrace occurs?

**Comment by bpross-52n** [comment]
The exception happens, because the content of the config.xml needs to be wrapped in a <config>-Element (see [here](https://github.com/opengeospatial/teamengine/blob/c2e9a3218443b888b8e1b99411857424b2e9328a/teamengine-core/src/main/java/com/occamlab/te/vocabulary/Config.java#L74)). The config.xml is "normally" created by the Teamengine webapp, which compiles the content of all available test suites into one file.

**Comment by dstenger** [comment]
After adding the wrapping `<config>` element, the test was successful with the same setup as described in https://github.com/opengeospatial/ets-wfs20/pull/245#pullrequestreview-1179373045:
```
stenger@elsbeere:~/git/ets-wfs20/target$ java -jar ets-wfs20-1.39-SNAPSHOT-aio.jar /home/stenger/test-run-props.xml
Nov 16, 2022 11:53:33 AM org.opengis.cite.iso19142.util.TestSuiteLogger log
INFORMATION: Using outputDirPath: /home/stenger
Nov 16, 2022 11:53:34 AM org.geotoolkit.referencing.factory.epsg.ThreadedEpsgFactory createBackingStore
INFORMATION: Connected to EPSG database “jdbc:derby:/home/stenger/.geotoolkit.org/EPSG/7.09” on “Apache Derby”.
Nov 16, 2022 11:53:35 AM com.sun.jersey.api.client.filter.LoggingFilter log
INFORMATION: 1 * Client out-bound request
1 > POST https://cite.deegree.org:443/deegree-webservices-3.4.30/services/wfs200
1 > Accept: application/xml,application/soap+xml
1 > Content-Type: application/soap+xml
...
```

@bpross-52n However, do you know why the wrapping `<config>` element is missing in this repository? Shouldn't it be added to following file? https://github.com/opengeospatial/ets-wfs20/blob/master/src/main/config/teamengine/config.xml

**Comment by bpross-52n** [comment]
Adding the <config> element to the config.xml of the WFS test suite leads to problems with the docker build. I will look into that.

**Comment by bpross-52n** [comment]
So this is where the problem occurs: [ConfigFileCreator ](https://github.com/opengeospatial/teamengine/blob/c2e9a3218443b888b8e1b99411857424b2e9328a/teamengine-web/src/main/java/com/occamlab/te/web/ConfigFileCreator.java#L163). The <organization> element needs to be the first element in the config.xml of a test suite.

**Comment by dstenger** [comment]
Decision during CITE meeting 2022-11-17:
@bpross-52n checks whether the config.xml can be packaged into the *aio.jar so that reference via environment variable is not necessary anymore.

**Pull request closed without merging**
